// -------------------------------------------------------------
// 
// File Name: D:\Advanced_Topic\untitled1\IIR_Filter.v
// Created: 2025-11-12 19:27:24
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.002
// Target subsystem base rate: 0.002
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.002
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.002
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: IIR_Filter
// Source Path: untitled1/IIR_Filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module IIR_Filter
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [23:0] In1;  // sfix24_En22
  output  ce_out;
  output  signed [39:0] Out1;  // sfix40_En30


  wire enb;
  wire signed [47:0] Gain2_out1;  // sfix48_En45
  wire signed [23:0] Data_Type_Conversion3_out1;  // sfix24_En22
  wire signed [47:0] Gain3_out1;  // sfix48_En44
  wire signed [23:0] Data_Type_Conversion4_out1;  // sfix24_En22
  wire signed [47:0] Gain4_out1;  // sfix48_En45
  wire signed [23:0] Data_Type_Conversion5_out1;  // sfix24_En22
  wire signed [39:0] Sum_out1;  // sfix40_En30
  wire signed [79:0] Gain_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion1_out1;  // sfix24_En22
  wire signed [79:0] Gain1_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion2_out1;  // sfix24_En22
  wire signed [31:0] Sum2_add_cast;  // sfix32_En22
  wire signed [31:0] Sum2_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum2_add_temp;  // sfix32_En22
  wire signed [39:0] Sum2_out1;  // sfix40_En30
  reg signed [39:0] Delay1_out1;  // sfix40_En30
  wire signed [39:0] Sum1_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum1_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum1_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum1_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum1_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum1_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum1_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum1_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum1_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum1_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum1_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum1_out1;  // sfix40_En30
  reg signed [39:0] Delay_out1;  // sfix40_En30
  wire signed [39:0] Sum_add_cast;  // sfix40_En30
  wire signed [40:0] Sum_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum_add_temp;  // sfix41_En30
  wire signed [79:0] Gain7_out1;  // sfix80_En77
  wire signed [23:0] Data_Type_Conversion8_out1;  // sfix24_En22
  wire signed [79:0] Gain8_out1;  // sfix80_En77
  wire signed [23:0] Data_Type_Conversion9_out1;  // sfix24_En22
  wire signed [79:0] Gain9_out1;  // sfix80_En77
  wire signed [23:0] Data_Type_Conversion10_out1;  // sfix24_En22
  wire signed [39:0] Sum3_out1;  // sfix40_En30
  wire signed [79:0] Gain5_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion6_out1;  // sfix24_En22
  wire signed [79:0] Gain6_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion7_out1;  // sfix24_En22
  wire signed [31:0] Sum5_add_cast;  // sfix32_En22
  wire signed [31:0] Sum5_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum5_add_temp;  // sfix32_En22
  wire signed [39:0] Sum5_out1;  // sfix40_En30
  reg signed [39:0] Delay3_out1;  // sfix40_En30
  wire signed [39:0] Sum4_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum4_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum4_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum4_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum4_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum4_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum4_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum4_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum4_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum4_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum4_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum4_out1;  // sfix40_En30
  reg signed [39:0] Delay2_out1;  // sfix40_En30
  wire signed [39:0] Sum3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum3_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum3_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum3_add_temp;  // sfix41_En30
  wire signed [79:0] Gain12_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion14_out1;  // sfix24_En22
  wire signed [79:0] Gain13_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion15_out1;  // sfix24_En22
  wire signed [79:0] Gain14_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion16_out1;  // sfix24_En22
  wire signed [39:0] Sum6_out1;  // sfix40_En30
  wire signed [79:0] Gain10_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion11_out1;  // sfix24_En22
  wire signed [79:0] Gain11_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion13_out1;  // sfix24_En22
  wire signed [31:0] Sum8_add_cast;  // sfix32_En22
  wire signed [31:0] Sum8_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum8_add_temp;  // sfix32_En22
  wire signed [39:0] Sum8_out1;  // sfix40_En30
  reg signed [39:0] Delay5_out1;  // sfix40_En30
  wire signed [39:0] Sum7_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum7_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum7_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum7_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum7_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum7_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum7_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum7_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum7_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum7_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum7_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum7_out1;  // sfix40_En30
  reg signed [39:0] Delay4_out1;  // sfix40_En30
  wire signed [39:0] Sum6_add_cast;  // sfix40_En30
  wire signed [40:0] Sum6_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum6_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum6_add_temp;  // sfix41_En30


  assign Gain2_out1 = 24'sb011111101010110001100110 * In1;


  assign Data_Type_Conversion3_out1 = (((Gain2_out1[47] == 1'b0) && (Gain2_out1[46] != 1'b0)) || ((Gain2_out1[47] == 1'b0) && (Gain2_out1[46:23] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain2_out1[47] == 1'b1) && (Gain2_out1[46] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain2_out1[46:23] + $signed({1'b0, Gain2_out1[22] & (( ~ Gain2_out1[47]) | (|Gain2_out1[21:0]))})));


  assign Gain3_out1 = 24'sb100110011000010011100000 * In1;


  assign Data_Type_Conversion4_out1 = (((Gain3_out1[47] == 1'b0) && (Gain3_out1[46:45] != 2'b00)) || ((Gain3_out1[47] == 1'b0) && (Gain3_out1[45:22] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain3_out1[47] == 1'b1) && (Gain3_out1[46:45] != 2'b11) ? 24'sb100000000000000000000000 :
              Gain3_out1[45:22] + $signed({1'b0, Gain3_out1[21] & (( ~ Gain3_out1[47]) | (|Gain3_out1[20:0]))})));


  assign Gain4_out1 = 24'sb011111101010110001100110 * In1;


  assign Data_Type_Conversion5_out1 = (((Gain4_out1[47] == 1'b0) && (Gain4_out1[46] != 1'b0)) || ((Gain4_out1[47] == 1'b0) && (Gain4_out1[46:23] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain4_out1[47] == 1'b1) && (Gain4_out1[46] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain4_out1[46:23] + $signed({1'b0, Gain4_out1[22] & (( ~ Gain4_out1[47]) | (|Gain4_out1[21:0]))})));


  assign enb = clk_enable;

  assign Gain_out1 = 40'sh667B200FB3 * Sum_out1;


  assign Data_Type_Conversion1_out1 = (((Gain_out1[79] == 1'b0) && (Gain_out1[78:69] != 10'b0000000000)) || ((Gain_out1[79] == 1'b0) && (Gain_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain_out1[79] == 1'b1) && (Gain_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain_out1[69:46] + $signed({1'b0, Gain_out1[45] & (( ~ Gain_out1[79]) | (|Gain_out1[44:0]))})));


  assign Gain1_out1 = 40'sh82A7341FE1 * Sum_out1;


  assign Data_Type_Conversion2_out1 = (((Gain1_out1[79] == 1'b0) && (Gain1_out1[78:70] != 9'b000000000)) || ((Gain1_out1[79] == 1'b0) && (Gain1_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain1_out1[79] == 1'b1) && (Gain1_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain1_out1[70:47] + $signed({1'b0, Gain1_out1[46] & (( ~ Gain1_out1[79]) | (|Gain1_out1[45:0]))})));


  assign Sum2_add_cast = {{8{Data_Type_Conversion5_out1[23]}}, Data_Type_Conversion5_out1};
  assign Sum2_add_cast_1 = {{8{Data_Type_Conversion2_out1[23]}}, Data_Type_Conversion2_out1};
  assign Sum2_add_temp = Sum2_add_cast + Sum2_add_cast_1;
  assign Sum2_out1 = {Sum2_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Sum2_out1;
        end
      end
    end


  assign Sum1_stage2_add_cast = {{8{Data_Type_Conversion4_out1[23]}}, {Data_Type_Conversion4_out1, 8'b00000000}};
  assign Sum1_stage2_add_cast_1 = {Sum1_stage2_add_cast[39], Sum1_stage2_add_cast};
  assign Sum1_stage2_add_cast_2 = {Delay1_out1[39], Delay1_out1};
  assign Sum1_stage2_add_temp = Sum1_stage2_add_cast_1 + Sum1_stage2_add_cast_2;
  assign Sum1_stage2_cast = ((Sum1_stage2_add_temp[40] == 1'b0) && (Sum1_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum1_stage2_add_temp[40] == 1'b1) && (Sum1_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum1_stage2_add_temp[39:0])));
  assign Sum1_op_stage1 = {Sum1_stage2_cast[39], Sum1_stage2_cast};



  assign Sum1_stage3_add_cast = ((Sum1_op_stage1[40] == 1'b0) && (Sum1_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum1_op_stage1[40] == 1'b1) && (Sum1_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum1_op_stage1[39:0])));
  assign Sum1_stage3_add_cast_1 = {Sum1_stage3_add_cast[39], Sum1_stage3_add_cast};
  assign Sum1_stage3_add_cast_2 = {{8{Data_Type_Conversion1_out1[23]}}, {Data_Type_Conversion1_out1, 8'b00000000}};
  assign Sum1_stage3_add_cast_3 = {Sum1_stage3_add_cast_2[39], Sum1_stage3_add_cast_2};
  assign Sum1_stage3_add_temp = Sum1_stage3_add_cast_1 + Sum1_stage3_add_cast_3;
  assign Sum1_out1 = ((Sum1_stage3_add_temp[40] == 1'b0) && (Sum1_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum1_stage3_add_temp[40] == 1'b1) && (Sum1_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum1_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Sum1_out1;
        end
      end
    end


  assign Sum_add_cast = {{8{Data_Type_Conversion3_out1[23]}}, {Data_Type_Conversion3_out1, 8'b00000000}};
  assign Sum_add_cast_1 = {Sum_add_cast[39], Sum_add_cast};
  assign Sum_add_cast_2 = {Delay_out1[39], Delay_out1};
  assign Sum_add_temp = Sum_add_cast_1 + Sum_add_cast_2;
  assign Sum_out1 = ((Sum_add_temp[40] == 1'b0) && (Sum_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum_add_temp[40] == 1'b1) && (Sum_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum_add_temp[39:0])));


  assign Gain7_out1 = 40'sh7CB0F59F13 * Sum_out1;


  assign Data_Type_Conversion8_out1 = (((Gain7_out1[79] == 1'b0) && (Gain7_out1[78] != 1'b0)) || ((Gain7_out1[79] == 1'b0) && (Gain7_out1[78:55] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain7_out1[79] == 1'b1) && (Gain7_out1[78] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain7_out1[78:55] + $signed({1'b0, Gain7_out1[54] & (( ~ Gain7_out1[79]) | (|Gain7_out1[53:0]))})));


  assign Gain8_out1 = 40'sh6BF47EFC08 * Sum_out1;


  assign Data_Type_Conversion9_out1 = (((Gain8_out1[79] == 1'b0) && (Gain8_out1[78] != 1'b0)) || ((Gain8_out1[79] == 1'b0) && (Gain8_out1[78:55] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain8_out1[79] == 1'b1) && (Gain8_out1[78] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain8_out1[78:55] + $signed({1'b0, Gain8_out1[54] & (( ~ Gain8_out1[79]) | (|Gain8_out1[53:0]))})));


  assign Gain9_out1 = 40'sh7CB0F59F13 * Sum_out1;


  assign Data_Type_Conversion10_out1 = (((Gain9_out1[79] == 1'b0) && (Gain9_out1[78] != 1'b0)) || ((Gain9_out1[79] == 1'b0) && (Gain9_out1[78:55] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain9_out1[79] == 1'b1) && (Gain9_out1[78] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain9_out1[78:55] + $signed({1'b0, Gain9_out1[54] & (( ~ Gain9_out1[79]) | (|Gain9_out1[53:0]))})));


  assign Gain5_out1 = 40'sh68BA2878F4 * Sum3_out1;


  assign Data_Type_Conversion6_out1 = (((Gain5_out1[79] == 1'b0) && (Gain5_out1[78:69] != 10'b0000000000)) || ((Gain5_out1[79] == 1'b0) && (Gain5_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain5_out1[79] == 1'b1) && (Gain5_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain5_out1[69:46] + $signed({1'b0, Gain5_out1[45] & (( ~ Gain5_out1[79]) | (|Gain5_out1[44:0]))})));


  assign Gain6_out1 = 40'shA5FAC4E77E * Sum3_out1;


  assign Data_Type_Conversion7_out1 = (((Gain6_out1[79] == 1'b0) && (Gain6_out1[78:70] != 9'b000000000)) || ((Gain6_out1[79] == 1'b0) && (Gain6_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain6_out1[79] == 1'b1) && (Gain6_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain6_out1[70:47] + $signed({1'b0, Gain6_out1[46] & (( ~ Gain6_out1[79]) | (|Gain6_out1[45:0]))})));


  assign Sum5_add_cast = {{8{Data_Type_Conversion10_out1[23]}}, Data_Type_Conversion10_out1};
  assign Sum5_add_cast_1 = {{8{Data_Type_Conversion7_out1[23]}}, Data_Type_Conversion7_out1};
  assign Sum5_add_temp = Sum5_add_cast + Sum5_add_cast_1;
  assign Sum5_out1 = {Sum5_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Sum5_out1;
        end
      end
    end


  assign Sum4_stage2_add_cast = {{8{Data_Type_Conversion9_out1[23]}}, {Data_Type_Conversion9_out1, 8'b00000000}};
  assign Sum4_stage2_add_cast_1 = {Sum4_stage2_add_cast[39], Sum4_stage2_add_cast};
  assign Sum4_stage2_add_cast_2 = {Delay3_out1[39], Delay3_out1};
  assign Sum4_stage2_add_temp = Sum4_stage2_add_cast_1 + Sum4_stage2_add_cast_2;
  assign Sum4_stage2_cast = ((Sum4_stage2_add_temp[40] == 1'b0) && (Sum4_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum4_stage2_add_temp[40] == 1'b1) && (Sum4_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum4_stage2_add_temp[39:0])));
  assign Sum4_op_stage1 = {Sum4_stage2_cast[39], Sum4_stage2_cast};



  assign Sum4_stage3_add_cast = ((Sum4_op_stage1[40] == 1'b0) && (Sum4_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum4_op_stage1[40] == 1'b1) && (Sum4_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum4_op_stage1[39:0])));
  assign Sum4_stage3_add_cast_1 = {Sum4_stage3_add_cast[39], Sum4_stage3_add_cast};
  assign Sum4_stage3_add_cast_2 = {{8{Data_Type_Conversion6_out1[23]}}, {Data_Type_Conversion6_out1, 8'b00000000}};
  assign Sum4_stage3_add_cast_3 = {Sum4_stage3_add_cast_2[39], Sum4_stage3_add_cast_2};
  assign Sum4_stage3_add_temp = Sum4_stage3_add_cast_1 + Sum4_stage3_add_cast_3;
  assign Sum4_out1 = ((Sum4_stage3_add_temp[40] == 1'b0) && (Sum4_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum4_stage3_add_temp[40] == 1'b1) && (Sum4_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum4_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Sum4_out1;
        end
      end
    end


  assign Sum3_add_cast = {{8{Data_Type_Conversion8_out1[23]}}, {Data_Type_Conversion8_out1, 8'b00000000}};
  assign Sum3_add_cast_1 = {Sum3_add_cast[39], Sum3_add_cast};
  assign Sum3_add_cast_2 = {Delay2_out1[39], Delay2_out1};
  assign Sum3_add_temp = Sum3_add_cast_1 + Sum3_add_cast_2;
  assign Sum3_out1 = ((Sum3_add_temp[40] == 1'b0) && (Sum3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum3_add_temp[40] == 1'b1) && (Sum3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum3_add_temp[39:0])));


  assign Gain12_out1 = {{2{Sum3_out1[39]}}, {Sum3_out1, 38'b00000000000000000000000000000000000000}};


  assign Data_Type_Conversion14_out1 = (((Gain12_out1[79] == 1'b0) && (Gain12_out1[78:69] != 10'b0000000000)) || ((Gain12_out1[79] == 1'b0) && (Gain12_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain12_out1[79] == 1'b1) && (Gain12_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain12_out1[69:46] + $signed({1'b0, Gain12_out1[45] & (( ~ Gain12_out1[79]) | (|Gain12_out1[44:0]))})));


  assign Gain13_out1 = 40'shA1BB3367EC * Sum3_out1;


  assign Data_Type_Conversion15_out1 = (((Gain13_out1[79] == 1'b0) && (Gain13_out1[78:70] != 9'b000000000)) || ((Gain13_out1[79] == 1'b0) && (Gain13_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain13_out1[79] == 1'b1) && (Gain13_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain13_out1[70:47] + $signed({1'b0, Gain13_out1[46] & (( ~ Gain13_out1[79]) | (|Gain13_out1[45:0]))})));


  assign Gain14_out1 = {{2{Sum3_out1[39]}}, {Sum3_out1, 38'b00000000000000000000000000000000000000}};


  assign Data_Type_Conversion16_out1 = (((Gain14_out1[79] == 1'b0) && (Gain14_out1[78:69] != 10'b0000000000)) || ((Gain14_out1[79] == 1'b0) && (Gain14_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain14_out1[79] == 1'b1) && (Gain14_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain14_out1[69:46] + $signed({1'b0, Gain14_out1[45] & (( ~ Gain14_out1[79]) | (|Gain14_out1[44:0]))})));


  assign Gain10_out1 = 40'sh69C697B3EC * Sum6_out1;


  assign Data_Type_Conversion11_out1 = (((Gain10_out1[79] == 1'b0) && (Gain10_out1[78:69] != 10'b0000000000)) || ((Gain10_out1[79] == 1'b0) && (Gain10_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain10_out1[79] == 1'b1) && (Gain10_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain10_out1[69:46] + $signed({1'b0, Gain10_out1[45] & (( ~ Gain10_out1[79]) | (|Gain10_out1[44:0]))})));


  assign Gain11_out1 = 40'sh8EE0E705A6 * Sum6_out1;


  assign Data_Type_Conversion13_out1 = (((Gain11_out1[79] == 1'b0) && (Gain11_out1[78:70] != 9'b000000000)) || ((Gain11_out1[79] == 1'b0) && (Gain11_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain11_out1[79] == 1'b1) && (Gain11_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain11_out1[70:47] + $signed({1'b0, Gain11_out1[46] & (( ~ Gain11_out1[79]) | (|Gain11_out1[45:0]))})));


  assign Sum8_add_cast = {{8{Data_Type_Conversion16_out1[23]}}, Data_Type_Conversion16_out1};
  assign Sum8_add_cast_1 = {{8{Data_Type_Conversion13_out1[23]}}, Data_Type_Conversion13_out1};
  assign Sum8_add_temp = Sum8_add_cast + Sum8_add_cast_1;
  assign Sum8_out1 = {Sum8_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= Sum8_out1;
        end
      end
    end


  assign Sum7_stage2_add_cast = {{8{Data_Type_Conversion15_out1[23]}}, {Data_Type_Conversion15_out1, 8'b00000000}};
  assign Sum7_stage2_add_cast_1 = {Sum7_stage2_add_cast[39], Sum7_stage2_add_cast};
  assign Sum7_stage2_add_cast_2 = {Delay5_out1[39], Delay5_out1};
  assign Sum7_stage2_add_temp = Sum7_stage2_add_cast_1 + Sum7_stage2_add_cast_2;
  assign Sum7_stage2_cast = ((Sum7_stage2_add_temp[40] == 1'b0) && (Sum7_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum7_stage2_add_temp[40] == 1'b1) && (Sum7_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum7_stage2_add_temp[39:0])));
  assign Sum7_op_stage1 = {Sum7_stage2_cast[39], Sum7_stage2_cast};



  assign Sum7_stage3_add_cast = ((Sum7_op_stage1[40] == 1'b0) && (Sum7_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum7_op_stage1[40] == 1'b1) && (Sum7_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum7_op_stage1[39:0])));
  assign Sum7_stage3_add_cast_1 = {Sum7_stage3_add_cast[39], Sum7_stage3_add_cast};
  assign Sum7_stage3_add_cast_2 = {{8{Data_Type_Conversion11_out1[23]}}, {Data_Type_Conversion11_out1, 8'b00000000}};
  assign Sum7_stage3_add_cast_3 = {Sum7_stage3_add_cast_2[39], Sum7_stage3_add_cast_2};
  assign Sum7_stage3_add_temp = Sum7_stage3_add_cast_1 + Sum7_stage3_add_cast_3;
  assign Sum7_out1 = ((Sum7_stage3_add_temp[40] == 1'b0) && (Sum7_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum7_stage3_add_temp[40] == 1'b1) && (Sum7_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum7_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Sum7_out1;
        end
      end
    end


  assign Sum6_add_cast = {{8{Data_Type_Conversion14_out1[23]}}, {Data_Type_Conversion14_out1, 8'b00000000}};
  assign Sum6_add_cast_1 = {Sum6_add_cast[39], Sum6_add_cast};
  assign Sum6_add_cast_2 = {Delay4_out1[39], Delay4_out1};
  assign Sum6_add_temp = Sum6_add_cast_1 + Sum6_add_cast_2;
  assign Sum6_out1 = ((Sum6_add_temp[40] == 1'b0) && (Sum6_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum6_add_temp[40] == 1'b1) && (Sum6_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum6_add_temp[39:0])));


  assign Out1 = Sum6_out1;

  assign ce_out = clk_enable;

endmodule  // IIR_Filter

