// -------------------------------------------------------------
// 
// File Name: D:\Advanced_Topic\Vivado\untitled1\IIR_Filter.v
// Created: 2025-10-31 21:45:31
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.1
// Target subsystem base rate: 0.1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: IIR_Filter
// Source Path: untitled1/IIR_Filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module IIR_Filter
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [23:0] In1;  // sfix24_En22
  output  ce_out;
  output  signed [39:0] Out1;  // sfix40_En30


  wire enb;
  wire signed [47:0] Gain2_out1;  // sfix48_En45
  wire signed [23:0] Data_Type_Conversion3_out1;  // sfix24_En22
  wire signed [47:0] Gain3_out1;  // sfix48_En44
  wire signed [23:0] Data_Type_Conversion4_out1;  // sfix24_En22
  wire signed [47:0] Gain4_out1;  // sfix48_En45
  wire signed [23:0] Data_Type_Conversion5_out1;  // sfix24_En22
  wire signed [39:0] Sum_out1;  // sfix40_En30
  wire signed [79:0] Gain_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion1_out1;  // sfix24_En22
  wire signed [79:0] Gain1_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion2_out1;  // sfix24_En22
  wire signed [31:0] Sum2_add_cast;  // sfix32_En22
  wire signed [31:0] Sum2_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum2_add_temp;  // sfix32_En22
  wire signed [39:0] Sum2_out1;  // sfix40_En30
  reg signed [39:0] Delay1_out1;  // sfix40_En30
  wire signed [39:0] Sum1_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum1_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum1_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum1_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum1_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum1_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum1_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum1_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum1_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum1_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum1_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum1_out1;  // sfix40_En30
  reg signed [39:0] Delay_out1;  // sfix40_En30
  wire signed [39:0] Sum_add_cast;  // sfix40_En30
  wire signed [40:0] Sum_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum_add_temp;  // sfix41_En30
  wire signed [79:0] Gain7_out1;  // sfix80_En77
  wire signed [23:0] Data_Type_Conversion8_out1;  // sfix24_En22
  wire signed [79:0] Gain8_out1;  // sfix80_En77
  wire signed [23:0] Data_Type_Conversion9_out1;  // sfix24_En22
  wire signed [79:0] Gain9_out1;  // sfix80_En77
  wire signed [23:0] Data_Type_Conversion10_out1;  // sfix24_En22
  wire signed [39:0] Sum3_out1;  // sfix40_En30
  wire signed [79:0] Gain5_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion6_out1;  // sfix24_En22
  wire signed [79:0] Gain6_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion7_out1;  // sfix24_En22
  wire signed [31:0] Sum5_add_cast;  // sfix32_En22
  wire signed [31:0] Sum5_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum5_add_temp;  // sfix32_En22
  wire signed [39:0] Sum5_out1;  // sfix40_En30
  reg signed [39:0] Delay3_out1;  // sfix40_En30
  wire signed [39:0] Sum4_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum4_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum4_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum4_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum4_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum4_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum4_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum4_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum4_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum4_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum4_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum4_out1;  // sfix40_En30
  reg signed [39:0] Delay2_out1;  // sfix40_En30
  wire signed [39:0] Sum3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum3_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum3_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum3_add_temp;  // sfix41_En30
  wire signed [79:0] Gain12_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion14_out1;  // sfix24_En22
  wire signed [79:0] Gain13_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion15_out1;  // sfix24_En22
  wire signed [79:0] Gain14_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion16_out1;  // sfix24_En22
  wire signed [39:0] Sum6_out1;  // sfix40_En30
  wire signed [79:0] Gain10_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion11_out1;  // sfix24_En22
  wire signed [79:0] Gain11_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion13_out1;  // sfix24_En22
  wire signed [31:0] Sum8_add_cast;  // sfix32_En22
  wire signed [31:0] Sum8_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum8_add_temp;  // sfix32_En22
  wire signed [39:0] Sum8_out1;  // sfix40_En30
  reg signed [39:0] Delay5_out1;  // sfix40_En30
  wire signed [39:0] Sum7_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum7_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum7_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum7_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum7_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum7_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum7_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum7_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum7_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum7_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum7_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum7_out1;  // sfix40_En30
  reg signed [39:0] Delay4_out1;  // sfix40_En30
  wire signed [39:0] Sum6_add_cast;  // sfix40_En30
  wire signed [40:0] Sum6_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum6_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum6_add_temp;  // sfix41_En30
  wire signed [79:0] Gain22_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion24_out1;  // sfix24_En22
  wire signed [79:0] Gain23_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion25_out1;  // sfix24_En22
  wire signed [79:0] Gain24_out1;  // sfix80_En1030
  wire signed [23:0] Data_Type_Conversion12_out1;  // sfix24_En22
  wire signed [39:0] Sum9_out1;  // sfix40_En30
  wire signed [79:0] Gain20_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion22_out1;  // sfix24_En22
  wire signed [79:0] Gain21_out1;  // sfix80_En1030
  wire signed [23:0] Data_Type_Conversion23_out1;  // sfix24_En22
  wire signed [31:0] Sum11_add_cast;  // sfix32_En22
  wire signed [31:0] Sum11_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum11_add_temp;  // sfix32_En22
  wire signed [39:0] Sum11_out1;  // sfix40_En30
  reg signed [39:0] Delay7_out1;  // sfix40_En30
  wire signed [39:0] Sum10_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum10_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum10_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum10_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum10_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum10_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum10_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum10_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum10_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum10_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum10_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum10_out1;  // sfix40_En30
  reg signed [39:0] Delay6_out1;  // sfix40_En30
  wire signed [39:0] Sum9_add_cast;  // sfix40_En30
  wire signed [40:0] Sum9_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum9_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum9_add_temp;  // sfix41_En30
  wire signed [79:0] Gain17_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion19_out1;  // sfix24_En22
  wire signed [79:0] Gain18_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion20_out1;  // sfix24_En22
  wire signed [79:0] Gain19_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion21_out1;  // sfix24_En22
  wire signed [39:0] Sum12_out1;  // sfix40_En30
  wire signed [79:0] Gain15_out1;  // sfix80_En68
  wire signed [23:0] Data_Type_Conversion17_out1;  // sfix24_En22
  wire signed [79:0] Gain16_out1;  // sfix80_En69
  wire signed [23:0] Data_Type_Conversion18_out1;  // sfix24_En22
  wire signed [31:0] Sum14_add_cast;  // sfix32_En22
  wire signed [31:0] Sum14_add_cast_1;  // sfix32_En22
  wire signed [31:0] Sum14_add_temp;  // sfix32_En22
  wire signed [39:0] Sum14_out1;  // sfix40_En30
  reg signed [39:0] Delay9_out1;  // sfix40_En30
  wire signed [39:0] Sum13_stage2_add_cast;  // sfix40_En30
  wire signed [40:0] Sum13_stage2_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum13_stage2_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum13_stage2_add_temp;  // sfix41_En30
  wire signed [39:0] Sum13_stage2_cast;  // sfix40_En30
  wire signed [40:0] Sum13_op_stage1;  // sfix41_En30
  wire signed [39:0] Sum13_stage3_add_cast;  // sfix40_En30
  wire signed [40:0] Sum13_stage3_add_cast_1;  // sfix41_En30
  wire signed [39:0] Sum13_stage3_add_cast_2;  // sfix40_En30
  wire signed [40:0] Sum13_stage3_add_cast_3;  // sfix41_En30
  wire signed [40:0] Sum13_stage3_add_temp;  // sfix41_En30
  wire signed [39:0] Sum13_out1;  // sfix40_En30
  reg signed [39:0] Delay8_out1;  // sfix40_En30
  wire signed [39:0] Sum12_add_cast;  // sfix40_En30
  wire signed [40:0] Sum12_add_cast_1;  // sfix41_En30
  wire signed [40:0] Sum12_add_cast_2;  // sfix41_En30
  wire signed [40:0] Sum12_add_temp;  // sfix41_En30


  assign Gain2_out1 = 24'sb011111101010110001100110 * In1;


  assign Data_Type_Conversion3_out1 = (((Gain2_out1[47] == 1'b0) && (Gain2_out1[46] != 1'b0)) || ((Gain2_out1[47] == 1'b0) && (Gain2_out1[46:23] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain2_out1[47] == 1'b1) && (Gain2_out1[46] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain2_out1[46:23] + $signed({1'b0, Gain2_out1[22]})));


  assign Gain3_out1 = 24'sb100110011000010011100000 * In1;


  assign Data_Type_Conversion4_out1 = (((Gain3_out1[47] == 1'b0) && (Gain3_out1[46:45] != 2'b00)) || ((Gain3_out1[47] == 1'b0) && (Gain3_out1[45:22] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain3_out1[47] == 1'b1) && (Gain3_out1[46:45] != 2'b11) ? 24'sb100000000000000000000000 :
              Gain3_out1[45:22] + $signed({1'b0, Gain3_out1[21]})));


  assign Gain4_out1 = 24'sb011111101010110001100110 * In1;


  assign Data_Type_Conversion5_out1 = (((Gain4_out1[47] == 1'b0) && (Gain4_out1[46] != 1'b0)) || ((Gain4_out1[47] == 1'b0) && (Gain4_out1[46:23] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain4_out1[47] == 1'b1) && (Gain4_out1[46] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain4_out1[46:23] + $signed({1'b0, Gain4_out1[22]})));


  assign enb = clk_enable;

  assign Gain_out1 = 40'sh667B200FB3 * Sum_out1;


  assign Data_Type_Conversion1_out1 = (((Gain_out1[79] == 1'b0) && (Gain_out1[78:69] != 10'b0000000000)) || ((Gain_out1[79] == 1'b0) && (Gain_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain_out1[79] == 1'b1) && (Gain_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain_out1[69:46] + $signed({1'b0, Gain_out1[45]})));


  assign Gain1_out1 = 40'sh82A7341FE1 * Sum_out1;


  assign Data_Type_Conversion2_out1 = (((Gain1_out1[79] == 1'b0) && (Gain1_out1[78:70] != 9'b000000000)) || ((Gain1_out1[79] == 1'b0) && (Gain1_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain1_out1[79] == 1'b1) && (Gain1_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain1_out1[70:47] + $signed({1'b0, Gain1_out1[46]})));


  assign Sum2_add_cast = {{8{Data_Type_Conversion5_out1[23]}}, Data_Type_Conversion5_out1};
  assign Sum2_add_cast_1 = {{8{Data_Type_Conversion2_out1[23]}}, Data_Type_Conversion2_out1};
  assign Sum2_add_temp = Sum2_add_cast + Sum2_add_cast_1;
  assign Sum2_out1 = {Sum2_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Sum2_out1;
        end
      end
    end


  assign Sum1_stage2_add_cast = {{8{Data_Type_Conversion4_out1[23]}}, {Data_Type_Conversion4_out1, 8'b00000000}};
  assign Sum1_stage2_add_cast_1 = {Sum1_stage2_add_cast[39], Sum1_stage2_add_cast};
  assign Sum1_stage2_add_cast_2 = {Delay1_out1[39], Delay1_out1};
  assign Sum1_stage2_add_temp = Sum1_stage2_add_cast_1 + Sum1_stage2_add_cast_2;
  assign Sum1_stage2_cast = ((Sum1_stage2_add_temp[40] == 1'b0) && (Sum1_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum1_stage2_add_temp[40] == 1'b1) && (Sum1_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum1_stage2_add_temp[39:0])));
  assign Sum1_op_stage1 = {Sum1_stage2_cast[39], Sum1_stage2_cast};



  assign Sum1_stage3_add_cast = ((Sum1_op_stage1[40] == 1'b0) && (Sum1_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum1_op_stage1[40] == 1'b1) && (Sum1_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum1_op_stage1[39:0])));
  assign Sum1_stage3_add_cast_1 = {Sum1_stage3_add_cast[39], Sum1_stage3_add_cast};
  assign Sum1_stage3_add_cast_2 = {{8{Data_Type_Conversion1_out1[23]}}, {Data_Type_Conversion1_out1, 8'b00000000}};
  assign Sum1_stage3_add_cast_3 = {Sum1_stage3_add_cast_2[39], Sum1_stage3_add_cast_2};
  assign Sum1_stage3_add_temp = Sum1_stage3_add_cast_1 + Sum1_stage3_add_cast_3;
  assign Sum1_out1 = ((Sum1_stage3_add_temp[40] == 1'b0) && (Sum1_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum1_stage3_add_temp[40] == 1'b1) && (Sum1_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum1_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Sum1_out1;
        end
      end
    end


  assign Sum_add_cast = {{8{Data_Type_Conversion3_out1[23]}}, {Data_Type_Conversion3_out1, 8'b00000000}};
  assign Sum_add_cast_1 = {Sum_add_cast[39], Sum_add_cast};
  assign Sum_add_cast_2 = {Delay_out1[39], Delay_out1};
  assign Sum_add_temp = Sum_add_cast_1 + Sum_add_cast_2;
  assign Sum_out1 = ((Sum_add_temp[40] == 1'b0) && (Sum_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum_add_temp[40] == 1'b1) && (Sum_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum_add_temp[39:0])));


  assign Gain7_out1 = 40'sh7CB0F59F13 * Sum_out1;


  assign Data_Type_Conversion8_out1 = (((Gain7_out1[79] == 1'b0) && (Gain7_out1[78] != 1'b0)) || ((Gain7_out1[79] == 1'b0) && (Gain7_out1[78:55] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain7_out1[79] == 1'b1) && (Gain7_out1[78] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain7_out1[78:55] + $signed({1'b0, Gain7_out1[54]})));


  assign Gain8_out1 = 40'sh6BF47EFC08 * Sum_out1;


  assign Data_Type_Conversion9_out1 = (((Gain8_out1[79] == 1'b0) && (Gain8_out1[78] != 1'b0)) || ((Gain8_out1[79] == 1'b0) && (Gain8_out1[78:55] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain8_out1[79] == 1'b1) && (Gain8_out1[78] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain8_out1[78:55] + $signed({1'b0, Gain8_out1[54]})));


  assign Gain9_out1 = 40'sh7CB0F59F13 * Sum_out1;


  assign Data_Type_Conversion10_out1 = (((Gain9_out1[79] == 1'b0) && (Gain9_out1[78] != 1'b0)) || ((Gain9_out1[79] == 1'b0) && (Gain9_out1[78:55] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain9_out1[79] == 1'b1) && (Gain9_out1[78] != 1'b1) ? 24'sb100000000000000000000000 :
              Gain9_out1[78:55] + $signed({1'b0, Gain9_out1[54]})));


  assign Gain5_out1 = 40'sh68BA2878F4 * Sum3_out1;


  assign Data_Type_Conversion6_out1 = (((Gain5_out1[79] == 1'b0) && (Gain5_out1[78:69] != 10'b0000000000)) || ((Gain5_out1[79] == 1'b0) && (Gain5_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain5_out1[79] == 1'b1) && (Gain5_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain5_out1[69:46] + $signed({1'b0, Gain5_out1[45]})));


  assign Gain6_out1 = 40'shA5FAC4E77E * Sum3_out1;


  assign Data_Type_Conversion7_out1 = (((Gain6_out1[79] == 1'b0) && (Gain6_out1[78:70] != 9'b000000000)) || ((Gain6_out1[79] == 1'b0) && (Gain6_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain6_out1[79] == 1'b1) && (Gain6_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain6_out1[70:47] + $signed({1'b0, Gain6_out1[46]})));


  assign Sum5_add_cast = {{8{Data_Type_Conversion10_out1[23]}}, Data_Type_Conversion10_out1};
  assign Sum5_add_cast_1 = {{8{Data_Type_Conversion7_out1[23]}}, Data_Type_Conversion7_out1};
  assign Sum5_add_temp = Sum5_add_cast + Sum5_add_cast_1;
  assign Sum5_out1 = {Sum5_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Sum5_out1;
        end
      end
    end


  assign Sum4_stage2_add_cast = {{8{Data_Type_Conversion9_out1[23]}}, {Data_Type_Conversion9_out1, 8'b00000000}};
  assign Sum4_stage2_add_cast_1 = {Sum4_stage2_add_cast[39], Sum4_stage2_add_cast};
  assign Sum4_stage2_add_cast_2 = {Delay3_out1[39], Delay3_out1};
  assign Sum4_stage2_add_temp = Sum4_stage2_add_cast_1 + Sum4_stage2_add_cast_2;
  assign Sum4_stage2_cast = ((Sum4_stage2_add_temp[40] == 1'b0) && (Sum4_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum4_stage2_add_temp[40] == 1'b1) && (Sum4_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum4_stage2_add_temp[39:0])));
  assign Sum4_op_stage1 = {Sum4_stage2_cast[39], Sum4_stage2_cast};



  assign Sum4_stage3_add_cast = ((Sum4_op_stage1[40] == 1'b0) && (Sum4_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum4_op_stage1[40] == 1'b1) && (Sum4_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum4_op_stage1[39:0])));
  assign Sum4_stage3_add_cast_1 = {Sum4_stage3_add_cast[39], Sum4_stage3_add_cast};
  assign Sum4_stage3_add_cast_2 = {{8{Data_Type_Conversion6_out1[23]}}, {Data_Type_Conversion6_out1, 8'b00000000}};
  assign Sum4_stage3_add_cast_3 = {Sum4_stage3_add_cast_2[39], Sum4_stage3_add_cast_2};
  assign Sum4_stage3_add_temp = Sum4_stage3_add_cast_1 + Sum4_stage3_add_cast_3;
  assign Sum4_out1 = ((Sum4_stage3_add_temp[40] == 1'b0) && (Sum4_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum4_stage3_add_temp[40] == 1'b1) && (Sum4_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum4_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Sum4_out1;
        end
      end
    end


  assign Sum3_add_cast = {{8{Data_Type_Conversion8_out1[23]}}, {Data_Type_Conversion8_out1, 8'b00000000}};
  assign Sum3_add_cast_1 = {Sum3_add_cast[39], Sum3_add_cast};
  assign Sum3_add_cast_2 = {Delay2_out1[39], Delay2_out1};
  assign Sum3_add_temp = Sum3_add_cast_1 + Sum3_add_cast_2;
  assign Sum3_out1 = ((Sum3_add_temp[40] == 1'b0) && (Sum3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum3_add_temp[40] == 1'b1) && (Sum3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum3_add_temp[39:0])));


  assign Gain12_out1 = {{2{Sum3_out1[39]}}, {Sum3_out1, 38'b00000000000000000000000000000000000000}};


  assign Data_Type_Conversion14_out1 = (((Gain12_out1[79] == 1'b0) && (Gain12_out1[78:69] != 10'b0000000000)) || ((Gain12_out1[79] == 1'b0) && (Gain12_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain12_out1[79] == 1'b1) && (Gain12_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain12_out1[69:46] + $signed({1'b0, Gain12_out1[45]})));


  assign Gain13_out1 = 40'shA1BB3367EC * Sum3_out1;


  assign Data_Type_Conversion15_out1 = (((Gain13_out1[79] == 1'b0) && (Gain13_out1[78:70] != 9'b000000000)) || ((Gain13_out1[79] == 1'b0) && (Gain13_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain13_out1[79] == 1'b1) && (Gain13_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain13_out1[70:47] + $signed({1'b0, Gain13_out1[46]})));


  assign Gain14_out1 = {{2{Sum3_out1[39]}}, {Sum3_out1, 38'b00000000000000000000000000000000000000}};


  assign Data_Type_Conversion16_out1 = (((Gain14_out1[79] == 1'b0) && (Gain14_out1[78:69] != 10'b0000000000)) || ((Gain14_out1[79] == 1'b0) && (Gain14_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain14_out1[79] == 1'b1) && (Gain14_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain14_out1[69:46] + $signed({1'b0, Gain14_out1[45]})));


  assign Gain10_out1 = 40'sh69C697B3EC * Sum6_out1;


  assign Data_Type_Conversion11_out1 = (((Gain10_out1[79] == 1'b0) && (Gain10_out1[78:69] != 10'b0000000000)) || ((Gain10_out1[79] == 1'b0) && (Gain10_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain10_out1[79] == 1'b1) && (Gain10_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain10_out1[69:46] + $signed({1'b0, Gain10_out1[45]})));


  assign Gain11_out1 = 40'sh8EE0E705A6 * Sum6_out1;


  assign Data_Type_Conversion13_out1 = (((Gain11_out1[79] == 1'b0) && (Gain11_out1[78:70] != 9'b000000000)) || ((Gain11_out1[79] == 1'b0) && (Gain11_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain11_out1[79] == 1'b1) && (Gain11_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain11_out1[70:47] + $signed({1'b0, Gain11_out1[46]})));


  assign Sum8_add_cast = {{8{Data_Type_Conversion16_out1[23]}}, Data_Type_Conversion16_out1};
  assign Sum8_add_cast_1 = {{8{Data_Type_Conversion13_out1[23]}}, Data_Type_Conversion13_out1};
  assign Sum8_add_temp = Sum8_add_cast + Sum8_add_cast_1;
  assign Sum8_out1 = {Sum8_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= Sum8_out1;
        end
      end
    end


  assign Sum7_stage2_add_cast = {{8{Data_Type_Conversion15_out1[23]}}, {Data_Type_Conversion15_out1, 8'b00000000}};
  assign Sum7_stage2_add_cast_1 = {Sum7_stage2_add_cast[39], Sum7_stage2_add_cast};
  assign Sum7_stage2_add_cast_2 = {Delay5_out1[39], Delay5_out1};
  assign Sum7_stage2_add_temp = Sum7_stage2_add_cast_1 + Sum7_stage2_add_cast_2;
  assign Sum7_stage2_cast = ((Sum7_stage2_add_temp[40] == 1'b0) && (Sum7_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum7_stage2_add_temp[40] == 1'b1) && (Sum7_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum7_stage2_add_temp[39:0])));
  assign Sum7_op_stage1 = {Sum7_stage2_cast[39], Sum7_stage2_cast};



  assign Sum7_stage3_add_cast = ((Sum7_op_stage1[40] == 1'b0) && (Sum7_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum7_op_stage1[40] == 1'b1) && (Sum7_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum7_op_stage1[39:0])));
  assign Sum7_stage3_add_cast_1 = {Sum7_stage3_add_cast[39], Sum7_stage3_add_cast};
  assign Sum7_stage3_add_cast_2 = {{8{Data_Type_Conversion11_out1[23]}}, {Data_Type_Conversion11_out1, 8'b00000000}};
  assign Sum7_stage3_add_cast_3 = {Sum7_stage3_add_cast_2[39], Sum7_stage3_add_cast_2};
  assign Sum7_stage3_add_temp = Sum7_stage3_add_cast_1 + Sum7_stage3_add_cast_3;
  assign Sum7_out1 = ((Sum7_stage3_add_temp[40] == 1'b0) && (Sum7_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum7_stage3_add_temp[40] == 1'b1) && (Sum7_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum7_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Sum7_out1;
        end
      end
    end


  assign Sum6_add_cast = {{8{Data_Type_Conversion14_out1[23]}}, {Data_Type_Conversion14_out1, 8'b00000000}};
  assign Sum6_add_cast_1 = {Sum6_add_cast[39], Sum6_add_cast};
  assign Sum6_add_cast_2 = {Delay4_out1[39], Delay4_out1};
  assign Sum6_add_temp = Sum6_add_cast_1 + Sum6_add_cast_2;
  assign Sum6_out1 = ((Sum6_add_temp[40] == 1'b0) && (Sum6_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum6_add_temp[40] == 1'b1) && (Sum6_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum6_add_temp[39:0])));


  assign Gain22_out1 = 40'sh7F01809E47 * Sum6_out1;


  assign Data_Type_Conversion24_out1 = (((Gain22_out1[79] == 1'b0) && (Gain22_out1[78:70] != 9'b000000000)) || ((Gain22_out1[79] == 1'b0) && (Gain22_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain22_out1[79] == 1'b1) && (Gain22_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain22_out1[70:47] + $signed({1'b0, Gain22_out1[46]})));


  assign Gain23_out1 = 40'sh80FE7F6053 * Sum6_out1;


  assign Data_Type_Conversion25_out1 = (((Gain23_out1[79] == 1'b0) && (Gain23_out1[78:70] != 9'b000000000)) || ((Gain23_out1[79] == 1'b0) && (Gain23_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain23_out1[79] == 1'b1) && (Gain23_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain23_out1[70:47] + $signed({1'b0, Gain23_out1[46]})));


  assign Gain24_out1 = 80'sh00000000000000000000;


  assign Data_Type_Conversion12_out1 = 24'sb000000000000000000000000;


  assign Gain20_out1 = 40'sh7E67236914 * Sum9_out1;


  assign Data_Type_Conversion22_out1 = (((Gain20_out1[79] == 1'b0) && (Gain20_out1[78:70] != 9'b000000000)) || ((Gain20_out1[79] == 1'b0) && (Gain20_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain20_out1[79] == 1'b1) && (Gain20_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain20_out1[70:47] + $signed({1'b0, Gain20_out1[46]})));


  assign Gain21_out1 = 80'sh00000000000000000000;


  assign Data_Type_Conversion23_out1 = 24'sb000000000000000000000000;


  assign Sum11_add_cast = {{8{Data_Type_Conversion12_out1[23]}}, Data_Type_Conversion12_out1};
  assign Sum11_add_cast_1 = {{8{Data_Type_Conversion23_out1[23]}}, Data_Type_Conversion23_out1};
  assign Sum11_add_temp = Sum11_add_cast + Sum11_add_cast_1;
  assign Sum11_out1 = {Sum11_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Sum11_out1;
        end
      end
    end


  assign Sum10_stage2_add_cast = {{8{Data_Type_Conversion25_out1[23]}}, {Data_Type_Conversion25_out1, 8'b00000000}};
  assign Sum10_stage2_add_cast_1 = {Sum10_stage2_add_cast[39], Sum10_stage2_add_cast};
  assign Sum10_stage2_add_cast_2 = {Delay7_out1[39], Delay7_out1};
  assign Sum10_stage2_add_temp = Sum10_stage2_add_cast_1 + Sum10_stage2_add_cast_2;
  assign Sum10_stage2_cast = ((Sum10_stage2_add_temp[40] == 1'b0) && (Sum10_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum10_stage2_add_temp[40] == 1'b1) && (Sum10_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum10_stage2_add_temp[39:0])));
  assign Sum10_op_stage1 = {Sum10_stage2_cast[39], Sum10_stage2_cast};



  assign Sum10_stage3_add_cast = ((Sum10_op_stage1[40] == 1'b0) && (Sum10_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum10_op_stage1[40] == 1'b1) && (Sum10_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum10_op_stage1[39:0])));
  assign Sum10_stage3_add_cast_1 = {Sum10_stage3_add_cast[39], Sum10_stage3_add_cast};
  assign Sum10_stage3_add_cast_2 = {{8{Data_Type_Conversion22_out1[23]}}, {Data_Type_Conversion22_out1, 8'b00000000}};
  assign Sum10_stage3_add_cast_3 = {Sum10_stage3_add_cast_2[39], Sum10_stage3_add_cast_2};
  assign Sum10_stage3_add_temp = Sum10_stage3_add_cast_1 + Sum10_stage3_add_cast_3;
  assign Sum10_out1 = ((Sum10_stage3_add_temp[40] == 1'b0) && (Sum10_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum10_stage3_add_temp[40] == 1'b1) && (Sum10_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum10_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay6_out1 <= Sum10_out1;
        end
      end
    end


  assign Sum9_add_cast = {{8{Data_Type_Conversion24_out1[23]}}, {Data_Type_Conversion24_out1, 8'b00000000}};
  assign Sum9_add_cast_1 = {Sum9_add_cast[39], Sum9_add_cast};
  assign Sum9_add_cast_2 = {Delay6_out1[39], Delay6_out1};
  assign Sum9_add_temp = Sum9_add_cast_1 + Sum9_add_cast_2;
  assign Sum9_out1 = ((Sum9_add_temp[40] == 1'b0) && (Sum9_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum9_add_temp[40] == 1'b1) && (Sum9_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum9_add_temp[39:0])));


  assign Gain17_out1 = {{2{Sum9_out1[39]}}, {Sum9_out1, 38'b00000000000000000000000000000000000000}};


  assign Data_Type_Conversion19_out1 = (((Gain17_out1[79] == 1'b0) && (Gain17_out1[78:69] != 10'b0000000000)) || ((Gain17_out1[79] == 1'b0) && (Gain17_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain17_out1[79] == 1'b1) && (Gain17_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain17_out1[69:46] + $signed({1'b0, Gain17_out1[45]})));


  assign Gain18_out1 = 40'sh800004F409 * Sum9_out1;


  assign Data_Type_Conversion20_out1 = (((Gain18_out1[79] == 1'b0) && (Gain18_out1[78:69] != 10'b0000000000)) || ((Gain18_out1[79] == 1'b0) && (Gain18_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain18_out1[79] == 1'b1) && (Gain18_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain18_out1[69:46] + $signed({1'b0, Gain18_out1[45]})));


  assign Gain19_out1 = 40'sh7FFFFFFE98 * Sum9_out1;


  assign Data_Type_Conversion21_out1 = (((Gain19_out1[79] == 1'b0) && (Gain19_out1[78:70] != 9'b000000000)) || ((Gain19_out1[79] == 1'b0) && (Gain19_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain19_out1[79] == 1'b1) && (Gain19_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain19_out1[70:47] + $signed({1'b0, Gain19_out1[46]})));


  assign Gain15_out1 = 40'sh7FCD490A96 * Sum12_out1;


  assign Data_Type_Conversion17_out1 = (((Gain15_out1[79] == 1'b0) && (Gain15_out1[78:69] != 10'b0000000000)) || ((Gain15_out1[79] == 1'b0) && (Gain15_out1[69:46] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain15_out1[79] == 1'b1) && (Gain15_out1[78:69] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              Gain15_out1[69:46] + $signed({1'b0, Gain15_out1[45]})));


  assign Gain16_out1 = 40'sh8064222C86 * Sum12_out1;


  assign Data_Type_Conversion18_out1 = (((Gain16_out1[79] == 1'b0) && (Gain16_out1[78:70] != 9'b000000000)) || ((Gain16_out1[79] == 1'b0) && (Gain16_out1[70:47] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain16_out1[79] == 1'b1) && (Gain16_out1[78:70] != 9'b111111111) ? 24'sb100000000000000000000000 :
              Gain16_out1[70:47] + $signed({1'b0, Gain16_out1[46]})));


  assign Sum14_add_cast = {{8{Data_Type_Conversion21_out1[23]}}, Data_Type_Conversion21_out1};
  assign Sum14_add_cast_1 = {{8{Data_Type_Conversion18_out1[23]}}, Data_Type_Conversion18_out1};
  assign Sum14_add_temp = Sum14_add_cast + Sum14_add_cast_1;
  assign Sum14_out1 = {Sum14_add_temp, 8'b00000000};


  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay9_out1 <= Sum14_out1;
        end
      end
    end


  assign Sum13_stage2_add_cast = {{8{Data_Type_Conversion20_out1[23]}}, {Data_Type_Conversion20_out1, 8'b00000000}};
  assign Sum13_stage2_add_cast_1 = {Sum13_stage2_add_cast[39], Sum13_stage2_add_cast};
  assign Sum13_stage2_add_cast_2 = {Delay9_out1[39], Delay9_out1};
  assign Sum13_stage2_add_temp = Sum13_stage2_add_cast_1 + Sum13_stage2_add_cast_2;
  assign Sum13_stage2_cast = ((Sum13_stage2_add_temp[40] == 1'b0) && (Sum13_stage2_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum13_stage2_add_temp[40] == 1'b1) && (Sum13_stage2_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum13_stage2_add_temp[39:0])));
  assign Sum13_op_stage1 = {Sum13_stage2_cast[39], Sum13_stage2_cast};



  assign Sum13_stage3_add_cast = ((Sum13_op_stage1[40] == 1'b0) && (Sum13_op_stage1[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum13_op_stage1[40] == 1'b1) && (Sum13_op_stage1[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum13_op_stage1[39:0])));
  assign Sum13_stage3_add_cast_1 = {Sum13_stage3_add_cast[39], Sum13_stage3_add_cast};
  assign Sum13_stage3_add_cast_2 = {{8{Data_Type_Conversion17_out1[23]}}, {Data_Type_Conversion17_out1, 8'b00000000}};
  assign Sum13_stage3_add_cast_3 = {Sum13_stage3_add_cast_2[39], Sum13_stage3_add_cast_2};
  assign Sum13_stage3_add_temp = Sum13_stage3_add_cast_1 + Sum13_stage3_add_cast_3;
  assign Sum13_out1 = ((Sum13_stage3_add_temp[40] == 1'b0) && (Sum13_stage3_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum13_stage3_add_temp[40] == 1'b1) && (Sum13_stage3_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum13_stage3_add_temp[39:0])));


  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= Sum13_out1;
        end
      end
    end


  assign Sum12_add_cast = {{8{Data_Type_Conversion19_out1[23]}}, {Data_Type_Conversion19_out1, 8'b00000000}};
  assign Sum12_add_cast_1 = {Sum12_add_cast[39], Sum12_add_cast};
  assign Sum12_add_cast_2 = {Delay8_out1[39], Delay8_out1};
  assign Sum12_add_temp = Sum12_add_cast_1 + Sum12_add_cast_2;
  assign Sum12_out1 = ((Sum12_add_temp[40] == 1'b0) && (Sum12_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Sum12_add_temp[40] == 1'b1) && (Sum12_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Sum12_add_temp[39:0])));


  assign Out1 = Sum12_out1;

  assign ce_out = clk_enable;

endmodule  // IIR_Filter

